#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID

killProcess() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid
while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'killProcess' SIGQUITgit 
done
